# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20160102_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noteimage',
            name='file',
        ),
    ]
